# -*- coding: utf-8 -*-
"""DL Self learning (24BAD114)ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DZJc9bbVSRidQ2TSLcEvm-jwsn-pZtE

**Import Libraries**
"""

!pip install -q gensim

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import PCA

import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences

from gensim.models import Word2Vec, FastText

import re
import time

print("Libraries imported successfully")

"""**Load the Dataset**"""

vocab_size = 10000

(x_train, y_train), (x_test, y_test) = imdb.load_data(
    num_words=vocab_size
)

print("Training samples:", len(x_train))
print("Testing samples:", len(x_test))

"""**Convert the IMDB sequences back to text**"""

word_index = imdb.get_word_index()

# Reverse the dictionary
reverse_word_index = {
    value + 3: key for key, value in word_index.items()
}

reverse_word_index[0] = "<PAD>"
reverse_word_index[1] = "<START>"
reverse_word_index[2] = "<UNK>"
reverse_word_index[3] = "<UNUSED>"

def decode_review(review):
    return " ".join(
        reverse_word_index.get(i, "<UNK>")
        for i in review
    )

train_text = [decode_review(review) for review in x_train[:5000]]

print(train_text[0][:1000])

"""**Text Cleaning**"""

def clean_text(text):
    text = text.lower()
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

cleaned_text = [clean_text(text) for text in train_text]

print(cleaned_text[0][:500])

"""**Tokenize the reviews**"""

tokenized_text = [
    sentence.split()
    for sentence in cleaned_text
]

print(tokenized_text[0][:20])

"""**TF-IDF**"""

tfidf_vectorizer = TfidfVectorizer(
    max_features=1000
)

tfidf_matrix = tfidf_vectorizer.fit_transform(cleaned_text)

print("TF-IDF shape:", tfidf_matrix.shape)

"""**See Important Words**"""

feature_names = tfidf_vectorizer.get_feature_names_out()

print("Number of features:", len(feature_names))
print("First 20 features:")
print(feature_names[:20])

"""**Word2Vec**"""

start_time = time.time()

word2vec_model = Word2Vec(
    sentences=tokenized_text,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    sg=1,
    epochs=10
)

word2vec_time = time.time() - start_time

print("Word2Vec training completed")
print("Training time:", round(word2vec_time, 2), "seconds")

"""Test Word2Vec"""

word = "good"

similar_words = word2vec_model.wv.most_similar(
    word,
    topn=5
)

print("Words similar to:", word)

for w, score in similar_words:
    print(w, round(score, 4))

"""**Five query words**"""

query_words = [
    "good",
    "movie",
    "film",
    "love",
    "bad"
]

for word in query_words:
    print("\nQuery word:", word)

    try:
        results = word2vec_model.wv.most_similar(
            word,
            topn=5
        )

        for similar_word, score in results:
            print(
                similar_word,
                round(score, 4)
            )

    except KeyError:
        print("Word not found in vocabulary")

"""**FastText**"""

start_time = time.time()

fasttext_model = FastText(
    sentences=tokenized_text,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    sg=1,
    epochs=10
)

fasttext_time = time.time() - start_time

print("FastText training completed")
print("Training time:", round(fasttext_time, 2), "seconds")

"""**FastText OOV Experiment**"""

oov_word = "wonderfullyamazing"

vector = fasttext_model.wv[oov_word]

print("Word:", oov_word)
print("Vector dimension:", len(vector))
print("First 10 values:")
print(vector[:10])

"""**Tensor Flow / Keras Embedding**"""

embedding_layer = tf.keras.layers.Embedding(
    input_dim=10000,
    output_dim=100
)

sample_input = tf.constant([
    [1, 2, 3, 4, 5]
])

embedding_output = embedding_layer(sample_input)

print("Embedding shape:")
print(embedding_output.shape)

"""**BERT**

Install
"""

!pip install -q transformers torch

"""Import"""

import torch
import numpy as np

from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries imported successfully")

"""Load BERT"""

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

model.eval()

print("BERT model loaded successfully")

"""Define the Two sentences"""

sentence1 = "I went to the bank to deposit money."
sentence2 = "We sat near the river bank."

print("Sentence 1:", sentence1)
print("Sentence 2:", sentence2)

"""Function to extract the word embedding"""

def get_word_embedding(sentence, target_word):

    inputs = tokenizer(
        sentence,
        return_tensors="pt"
    )

    with torch.no_grad():
        outputs = model(**inputs)

    tokens = tokenizer.convert_ids_to_tokens(
        inputs["input_ids"][0]
    )

    target_tokens = tokenizer.tokenize(target_word)

    target_positions = []

    for i in range(len(tokens)):
        if tokens[i] in target_tokens:
            target_positions.append(i)

    if len(target_positions) == 0:
        raise ValueError(
            f"'{target_word}' was not found in the sentence."
        )

    # Use the first matching token
    position = target_positions[0]

    embedding = outputs.last_hidden_state[
        0, position, :
    ]

    return embedding, tokens

"""Extract "bank" embeddings"""

embedding1, tokens1 = get_word_embedding(
    sentence1,
    "bank"
)

embedding2, tokens2 = get_word_embedding(
    sentence2,
    "bank"
)

print("Sentence 1 tokens:")
print(tokens1)

print("\nSentence 2 tokens:")
print(tokens2)

print("\nEmbedding 1 shape:")
print(embedding1.shape)

print("\nEmbedding 2 shape:")
print(embedding2.shape)

"""Calculate Cosine similarity"""

vector1 = embedding1.detach().numpy().reshape(1, -1)
vector2 = embedding2.detach().numpy().reshape(1, -1)

similarity = cosine_similarity(
    vector1,
    vector2
)[0][0]

print("Cosine similarity:",
      round(float(similarity), 4))

"""Final BERT result"""

print("BERT Contextual Embedding Experiment")
print("-------------------------------------")

print("\nContext 1:")
print(sentence1)

print("\nContext 2:")
print(sentence2)

print("\nTarget word: bank")

print(
    "\nCosine similarity between the two "
    "contextual representations:",
    round(float(similarity), 4)
)

"""**Visualization**"""

words = list(word2vec_model.wv.index_to_key[:50])

vectors = np.array([
    word2vec_model.wv[word]
    for word in words
])

pca = PCA(n_components=2)

reduced_vectors = pca.fit_transform(vectors)

plt.figure(figsize=(12, 8))

plt.scatter(
    reduced_vectors[:, 0],
    reduced_vectors[:, 1]
)

for i, word in enumerate(words):
    plt.annotate(
        word,
        (reduced_vectors[i, 0],
         reduced_vectors[i, 1])
    )

plt.title("Word2Vec Embeddings Visualized Using PCA")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

"""**Comparison**"""

#Comparison of Text Representation Techniques

import pandas as pd

comparison_data = {
    "Technique": [
        "TF-IDF",
        "Word2Vec",
        "FastText",
        "Keras Embedding",
        "BERT"
    ],

    "Representation": [
        "Sparse numerical vectors",
        "Dense 100-dimensional vectors",
        "Dense 100-dimensional subword vectors",
        "Dense 100-dimensional vectors",
        "Dense 768-dimensional contextual vectors"
    ],

    "Semantic Understanding": [
        "Low to Moderate",
        "High",
        "High",
        "Depends on training",
        "Very High"
    ],

    "OOV Handling": [
        "Limited",
        "Poor",
        "Good",
        "Limited",
        "Good"
    ],

    "Contextual Understanding": [
        "No",
        "No",
        "No",
        "Depends on model",
        "Yes"
    ],

    "Computational Requirement": [
        "Low",
        "Moderate",
        "Moderate to High",
        "Low to Moderate",
        "High"
    ]
}

comparison_df = pd.DataFrame(comparison_data)

print("COMPARISON OF TEXT REPRESENTATION TECHNIQUES")
print("=" * 70)

display(comparison_df)

# Experimental Results

results = {
    "Technique": [
        "TF-IDF",
        "Word2Vec",
        "FastText",
        "Keras Embedding",
        "BERT"
    ],

    "Observed Result": [
        "Matrix shape: (5000, 1000)",
        "Training time: 68.3 seconds",
        "Training time: 134.6 seconds",
        "Output shape: (1, 5, 100)",
        "Embedding size: 768, Cosine similarity: 0.5411"
    ]
}

results_df = pd.DataFrame(results)

print("\nEXPERIMENTAL RESULTS")
print("=" * 70)

display(results_df)

"""**Analysis and Conclusion**

### Analysis

The experiments demonstrate the differences between traditional, static, neural, and contextual word representations.

TF-IDF represents documents using numerical weights based on the importance of words. It is simple and computationally efficient, but it does not capture semantic relationships or the context in which a word is used.

Word2Vec generates dense word vectors that capture semantic relationships between words. In the experiment, words such as "movie" and "film" showed a strong semantic relationship. For example, "film" was the most similar word to "movie", with a cosine similarity of 0.8836.

FastText extends the Word2Vec approach by representing words using character-level subword information. This makes it more effective for rare and out-of-vocabulary words. In the experiment, the word "wonderfullyamazing" produced a 100-dimensional vector even though it was not necessarily present as a complete word in the training vocabulary.

The TensorFlow/Keras Embedding layer generated dense trainable word representations. The experiment produced an embedding output of shape (1, 5, 100), demonstrating how integer token sequences can be transformed into dense vectors.

BERT provides contextual word representations. The word "bank" was tested in two different contexts: a financial context and a river-related context. The resulting representations were 768-dimensional, and their cosine similarity was 0.5411. This demonstrates that BERT represents words according to their surrounding context rather than assigning one fixed representation to a word.

### PCA Visualization

PCA was used to reduce the 100-dimensional Word2Vec representations to two dimensions. The resulting visualization provides a way to inspect relationships and possible semantic clusters among the selected words.

Words that appear close to each other in the visualization can indicate similar patterns learned from the text corpus. However, PCA is only a two-dimensional projection of the original embedding space, so visual distance should be interpreted as an approximate representation of the original relationships.

### Overall Comparison

TF-IDF is useful for simple text representation and traditional machine-learning applications. Word2Vec provides better semantic relationships through dense word vectors. FastText improves handling of rare and unseen words by using subword information. Keras Embedding provides a flexible trainable representation that can be incorporated into neural networks. BERT provides the strongest contextual representation among the techniques explored, but it also requires considerably more computational resources.

### Conclusion

The experiments show the progression from traditional text representation to modern contextual embeddings. TF-IDF provides an efficient frequency-based representation, while Word2Vec and FastText provide dense semantic representations. FastText is particularly useful when handling rare or unseen words. BERT goes further by generating contextual representations that depend on the surrounding sentence.

Therefore, there is no single representation that is best for every application. TF-IDF is suitable when simplicity and efficiency are important, Word2Vec and FastText are useful for semantic word relationships, and BERT is more suitable when contextual understanding is required.
"""